version: '3.8'

services:
  # Main evaluation service (supports both standard and Ray modes)
  som-evaluation:
    build:
      context: .
      target: evaluation
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./contexts:/app/contexts
      - ./logs:/app/logs
    environment:
      - RAY_ADDRESS=ray-head:10001
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - COHERE_API_KEY=${COHERE_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ray-head
    command: tail -f /dev/null  # Keep container running

  # Ray cluster head node
  ray-head:
    build:
      context: .
      target: production
    ports:
      - "8265:8265"  # Ray dashboard
      - "10001:10001"  # Ray client port
    environment:
      - RAY_DISABLE_IMPORT_WARNING=1
    volumes:
      - ./logs:/app/logs
    command: >
      ray start --head 
      --port=6379 
      --object-manager-port=8076 
      --dashboard-host=0.0.0.0 
      --dashboard-port=8265
      --disable-usage-stats
      --block

  # Ray worker nodes
  ray-worker:
    build:
      context: .
      target: production
    environment:
      - RAY_DISABLE_IMPORT_WARNING=1
    volumes:
      - ./logs:/app/logs
    depends_on:
      - ray-head
    deploy:
      replicas: 2
    command: >
      ray start --address=ray-head:6379 --block

  # Jupyter for development
  jupyter:
    build:
      context: .
      target: development
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - COHERE_API_KEY=${COHERE_API_KEY:-}
    profiles:
      - development
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser 
      --allow-root --NotebookApp.token='' --NotebookApp.password=''

networks:
  default:
    driver: bridge
